### ISSUE TITLE
Double clicking date changes the year to 1969

### ISSUE THREAD

**Issue by vediga** [kekeh/mydatepicker#339] opened 2017-06-12 18:32 UTC
In my usecase I use the date picker component (calendar) always open to the left and input fields next to the calendar so once user changes the date the input fields get updated based on the selected date. I am noticing a bug where if user by mistake double clicks any date the date is moved back to **Wed Dec 31 1969** so now both calendar and the input fields show this date **Wed Dec 31 1969**.

If user clicks only once to change to a new date everything works fine. But say you are on day 20 (which is currently selected) but if you click on the same day 20 then calendar is set back to dec 31 1969

**Comment by kekeh** [comment] 2017-06-15 07:34
I am not able to reproduce this issue. Can you reproduce it here: http://kekeh.github.io/mydatepicker

Can you update mydatepicker to the latest version.

**Comment by kekeh** [comment] 2017-06-19 11:38
I close this issue because no answer. If you still have the same problem you can reopen the issue.

**Closed by kekeh** 2017-06-19 11:38 UTC

**Comment by vediga** [comment] 2017-06-19 17:31
I figured out what was going wrong...
When I click the already selected date "dateChanged" output passes and object which looks like this Object {date: Object, jsdate: null, formatted: "", epoc: 0}. I think I was using that object to set the date on the input field without checking if it is null.

I think this is a bug because "dateChanged" event should not be emitted if date has not changed i.e is user selects already selected date.

**Comment by kekeh** [comment] 2017-06-20 04:19
You can set option **allowDeselectDate** to **false** or update mydatepicker to the latest version where the option is already false.
